### PR TITLE
Bump phoenix versoin to 1.1 and phoenix_html to 2.3

### PR DESCRIPTION
**Pull request by programisti**

### CODE REVIEW

**Comment by cseeger** [comment]
👍

**Comment by chrismccord** [comment]
This should be good for 1.0 or 1.1, please update and I'll merge. Thanks!

**Comment by mgwidmann** [comment]
any progress on this?

**Comment by programisti** [comment]
@chrismccord I already have bumped phoenix version to 1.1
https://github.com/programisti/phoenix_haml/commit/08b8a60c68ea6285f59fa80381e219451ca32746#diff-6023be6004fce4718dad3dafb576d258R27

**Pull request merged**
