### PR TITLE
Added generator: $ mix phoenix_haml.gen.html

### PR DESCRIPTION
**Pull request by parndt**
This works in the same manner as `$ mix phoenix.gen.html` but will produce HAML templates in place of the default eex ones.

Example:

```
$ mix phoenix_haml.gen.html MyHamlThing my_haml_things name:string
* creating web/controllers/my_haml_thing_controller.ex
* creating test/controllers/my_haml_thing_controller_test.exs
* creating web/views/my_haml_thing_view.ex
* creating web/templates/my_haml_thing/edit.html.haml
* creating web/templates/my_haml_thing/form.html.haml
* creating web/templates/my_haml_thing/index.html.haml
* creating web/templates/my_haml_thing/new.html.haml
* creating web/templates/my_haml_thing/show.html.haml
* creating web/models/my_haml_thing.ex
* creating test/models/my_haml_thing_test.exs
* creating priv/repo/migrations/20160226220620_create_my_haml_thing.exs

Add the resource to your browser scope in web/router.ex:

    resources "/my_haml_things", MyHamlThingController

Remember to update your repository by running migrations:

    $ mix ecto.migrate

```

This replaces phoenixframework/phoenix#1568

It would be good if the generator from phoenix has `defoverridable` or `__using__` so that all of this code doesn't have to be copy pasted for every different template language that needs a generator, but currently that's the way it is.

The team at Manuka Coalition (@manukaco) are happy to maintain this generator.

### CODE REVIEW

**Comment by chrismccord** [comment]
The task should be `phoenix_haml.gen.html`

**Comment by parndt** [comment]
@chrismccord it has been so renamed

**Comment by parndt** [comment]
Any chance we can enable Travis CI for this repo? https://travis-ci.org/chrismccord/phoenix_haml :heart:

**Comment by parndt** [comment]
@chrismccord anything else that you'd like done to this PR?

**Comment by smpallen99** [comment]
I wrote a haml generator, and it looks very similar to this one. I've reviewed the code and only have one comment. In the index template, you should use `- for ...`, instead of `= for ....`. Calliope was designed to use `-`. Other than that, I would like to see this pull request merged.

Steve

**Comment by parndt** [comment]
@smpallen99 great feedback, that does work!

**Pull request merged**
